# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\User\Documents\VS_Code\HorseRiding\name_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_riding_list_window(object):
    def setupUi(self, riding_list_window):
        riding_list_window.setObjectName("riding_list_window")
        riding_list_window.resize(482, 681)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(riding_list_window.sizePolicy().hasHeightForWidth())
        riding_list_window.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget = QtWidgets.QWidget(riding_list_window)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 461, 26))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.writeButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.writeButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.writeButton.setObjectName("writeButton")
        self.horizontalLayout.addWidget(self.writeButton)
        self.verticalLayoutWidget = QtWidgets.QWidget(riding_list_window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 41, 461, 631))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView_name = QtWidgets.QTableView(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_name.sizePolicy().hasHeightForWidth())
        self.tableView_name.setSizePolicy(sizePolicy)
        self.tableView_name.setMinimumSize(QtCore.QSize(0, 0))
        self.tableView_name.setBaseSize(QtCore.QSize(0, 0))
        self.tableView_name.setObjectName("tableView_name")
        self.tableView_name.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout_2.addWidget(self.tableView_name)

        self.retranslateUi(riding_list_window)
        QtCore.QMetaObject.connectSlotsByName(riding_list_window)

    def retranslateUi(self, riding_list_window):
        _translate = QtCore.QCoreApplication.translate
        riding_list_window.setWindowTitle(_translate("riding_list_window", "riding_times"))
        self.writeButton.setText(_translate("riding_list_window", "書込"))
